[package]
name = "gores-mapgen-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
notan = { version = "0.12.0", features = ["egui"] }

[profile.release]
opt-level = 2
